
platform :ios, '9.0'

target 'TuyaSmartHomeKit_Example' do

  pod 'TuyaSmartHomeKit'
  pod 'TuyaSmartCameraKit'
  pod 'TYCameraCloudServicePanelSDK'
  
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'BlocksKit'
  pod 'SDWebImage'
  pod 'Reachability'
  pod 'Masonry'

  target 'TuyaSmartHomeKit_Tests' do
    inherit! :search_paths

  end
end
