# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TuyaCameraDemo' do

	pod 'TuyaSmartDemo', :path => '../', :subspecs => [
	'Base',
  	'Login',
  	'DeviceList',
  	'AddDevice',
  	'UserInfo',
  	'IPC']
  
end
